---
columns:
  - movie_name
  - year
  - rating
  - one_line
  - runtime
  - gross

sink:
  host: localhost
  port: 5432 
  username: ${username}
  password: ${password}
  database: CAD_IT
  schema: movies_dw
  table: fact_movies
  method: extract