---
columns:
  - movie_name
  - year 
  - genre
  - director 
  - stars
  - rating
  - one_line 
  - runtime
  - gross 

sink:
  host: localhost
  port: 5432 
  username: postgres
  password: ${password}
  database: CAD_IT
  schema: movies_dw
  table: raw_movies
  method: extract