columns:
  - movie_id
  - star_id

sink:
  host: localhost
  username: postgres
  port: 5432
  
  password: ${password}
  database: CAD_IT
  schema: movies_dw
  method: junction_sql
  table: junction_movie_stars
  dim_table: dim_stars
  join_col: stars
