columns:
  - movie_id
  - director_id

sink:
  host: localhost
  port: 5432
  username: ${username}
  password: ${password}
  database: CAD_IT
  schema: movies_dw
  method: junction_sql
  table: junction_movie_directors
  dim_table: dim_directors
  join_col: director